//! Render the tool catalog from the descriptors the server actually serves.
//!
//! The reference is generated rather than written because a hand-maintained
//! one drifts the first time a schema changes, and a tool reference that
//! disagrees with the server is worse than none: an agent's author reads it and
//! sends arguments the tool will reject.
//!
//! Output is deterministic — registry order is insertion order, and the JSON
//! renderer preserves nothing that varies between runs — so CI can assert the
//! committed file still matches.

use mcp_types::{Category, ToolDescriptor};
use serde_json::Value;

/// Categories in the order they should appear, so the document reads
/// perception → action → everything else rather than in registration order.
fn category_rank(c: Category) -> usize {
    match c {
        Category::Vision => 0,
        Category::Input => 1,
        Category::Window => 2,
        Category::Desktop => 3,
        Category::Browser => 4,
        Category::Terminal => 5,
        Category::Filesystem => 6,
        Category::Network => 7,
        Category::System => 8,
        Category::Packages => 9,
        Category::Credentials => 10,
        Category::Memory => 11,
    }
}

fn tier_str(d: &ToolDescriptor) -> &'static str {
    match d.tier {
        mcp_types::Tier::Read => "read",
        mcp_types::Tier::Standard => "standard",
        mcp_types::Tier::Dangerous => "dangerous",
    }
}

/// First sentence of a description, for the summary table.
fn summary(desc: &str) -> String {
    let one_line = desc.replace('\n', " ");
    let cut = one_line
        .find(". ")
        .map(|i| i + 1)
        .unwrap_or(one_line.len().min(140));
    let s = one_line[..cut].trim().to_string();
    if s.len() < one_line.trim().len() && !s.ends_with('.') {
        format!("{s}…")
    } else {
        s
    }
}

/// A JSON-Schema type rendered for a table cell: `string`, `array<string>`,
/// `object`, or `one of: a, b`.
fn type_of(spec: &Value) -> String {
    if let Some(e) = spec.get("enum").and_then(Value::as_array) {
        let names: Vec<String> = e
            .iter()
            .map(|v| v.as_str().unwrap_or_default().to_string())
            .collect();
        return format!("one of: {}", names.join(", "));
    }
    let t = spec.get("type").and_then(Value::as_str).unwrap_or("any");
    if t == "array" {
        let inner = spec
            .get("items")
            .map(type_of)
            .unwrap_or_else(|| "any".into());
        return format!("array&lt;{inner}&gt;");
    }
    t.to_string()
}

/// Escape the few characters that would break a Markdown table cell.
fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// One row per argument, with nested object properties as dotted names so the
/// shape is legible without reading the raw schema.
fn arg_rows(prefix: &str, props: &Value, required: &[String], out: &mut Vec<String>) {
    let Some(map) = props.as_object() else { return };
    for (name, spec) in map {
        let full = if prefix.is_empty() {
            name.clone()
        } else {
            format!("{prefix}.{name}")
        };
        let req = if prefix.is_empty() && required.iter().any(|r| r == name) {
            "yes"
        } else {
            ""
        };
        let desc = spec
            .get("description")
            .and_then(Value::as_str)
            .unwrap_or_default();
        out.push(format!(
            "| `{}` | {} | {} | {} |",
            full,
            type_of(spec),
            req,
            cell(desc)
        ));
        if spec.get("type").and_then(Value::as_str) == Some("object") {
            if let Some(inner) = spec.get("properties") {
                arg_rows(&full, inner, &[], out);
            }
        }
    }
}

/// The full Markdown reference.
pub fn render_markdown(tools: &[ToolDescriptor]) -> String {
    let mut sorted: Vec<&ToolDescriptor> = tools.iter().collect();
    sorted.sort_by_key(|d| (category_rank(d.category), d.name.clone()));

    let mut s = String::new();
    s.push_str("<!-- Generated by `agentctl tools --markdown --all`. Do not edit by hand. -->\n\n");
    s.push_str("# agentctl tool reference\n\n");
    s.push_str(
        "Every tool the server can expose, with its category, safety tier and arguments.\n\n\
         Tiers gate what an agent may call: `read` and `standard` tools are available inside an\n\
         enabled category, while a `dangerous` tool additionally has to be named in\n\
         `policy.enable`. Enabling a category never enables its dangerous tools.\n\n",
    );
    s.push_str(&format!(
        "**{} tools across {} categories.**\n\n",
        sorted.len(),
        sorted
            .iter()
            .map(|d| d.category.slug())
            .collect::<std::collections::BTreeSet<_>>()
            .len()
    ));

    s.push_str("| Tool | Category | Tier | Summary |\n|---|---|---|---|\n");
    for d in &sorted {
        s.push_str(&format!(
            "| [`{}`](#{}) | {} | {} | {} |\n",
            d.name,
            d.name.replace('_', "-"),
            d.category.slug(),
            tier_str(d),
            cell(&summary(&d.description))
        ));
    }

    let mut current: Option<Category> = None;
    for d in &sorted {
        if current != Some(d.category) {
            current = Some(d.category);
            s.push_str(&format!("\n## {}\n", d.category.slug()));
        }
        s.push_str(&format!("\n### {}\n\n", d.name.replace('_', "-")));
        s.push_str(&format!("`{}` · {} tier\n\n", d.name, tier_str(d)));
        s.push_str(&format!("{}\n\n", d.description));
        if let Some(details) = &d.details {
            s.push_str(&format!("{details}\n\n"));
        }

        let required: Vec<String> = d
            .input_schema
            .get("required")
            .and_then(Value::as_array)
            .map(|a| {
                a.iter()
                    .filter_map(Value::as_str)
                    .map(str::to_string)
                    .collect()
            })
            .unwrap_or_default();
        let mut rows = Vec::new();
        if let Some(props) = d.input_schema.get("properties") {
            arg_rows("", props, &required, &mut rows);
        }
        if rows.is_empty() {
            s.push_str("No arguments.\n");
        } else {
            s.push_str("| Argument | Type | Required | Description |\n|---|---|---|---|\n");
            for r in rows {
                s.push_str(&r);
                s.push('\n');
            }
        }
    }
    s
}

/// The same catalog as JSON, for anything that would rather parse than read.
pub fn render_json(tools: &[ToolDescriptor]) -> String {
    let arr: Vec<Value> = tools
        .iter()
        .map(|d| {
            serde_json::json!({
                "name": d.name,
                "category": d.category.slug(),
                "tier": tier_str(d),
                "description": d.description,
                "input_schema": d.input_schema,
            })
        })
        .collect();
    serde_json::to_string_pretty(&arr).unwrap_or_else(|_| "[]".into())
}

#[cfg(test)]
mod tests {
    use super::*;
    use mcp_types::Tier;
    use serde_json::json;

    fn fixture() -> Vec<ToolDescriptor> {
        vec![
            ToolDescriptor::new(
                "zzz_read",
                Category::Vision,
                Tier::Read,
                "Look at something. Extra detail after the first sentence.",
                json!({"type":"object","properties":{
                    "region": {"type":"object","properties":{"x":{"type":"number"}}},
                    "mode": {"type":"string","enum":["a","b"],"description":"which | mode"}
                },"required":["mode"]}),
            )
            .details("Docs-only caveat for the reference."),
            ToolDescriptor::new(
                "aaa_danger",
                Category::Credentials,
                Tier::Dangerous,
                "Do something risky.",
                json!({"type":"object","properties":{},"required":[]}),
            ),
        ]
    }

    #[test]
    fn categories_lead_and_tools_sort_within_them() {
        let md = render_markdown(&fixture());
        let vision = md.find("## vision").unwrap();
        let creds = md.find("## credentials").unwrap();
        assert!(vision < creds, "perception categories come first");
    }

    #[test]
    fn arguments_render_with_nesting_enums_and_required() {
        let md = render_markdown(&fixture());
        assert!(md.contains("| `mode` | one of: a, b | yes |"));
        assert!(md.contains("| `region` | object |"));
        assert!(md.contains("| `region.x` | number |"));
        // A pipe inside a description must not break the table.
        assert!(md.contains("which \\| mode"));
    }

    #[test]
    fn details_render_after_the_description_and_only_there() {
        let md = render_markdown(&fixture());
        let desc = md.find("Look at something. Extra detail").unwrap();
        let details = md.find("Docs-only caveat for the reference.").unwrap();
        let table = md.find("| Argument |").unwrap();
        assert!(desc < details && details < table);
        // The one-line summary table stays a summary.
        assert_eq!(md.matches("Docs-only caveat").count(), 1);
        assert!(!render_json(&fixture()).contains("Docs-only caveat"));
    }

    #[test]
    fn a_tool_without_arguments_says_so() {
        let md = render_markdown(&fixture());
        assert!(md.contains("No arguments."));
    }

    #[test]
    fn rendering_is_deterministic() {
        assert_eq!(render_markdown(&fixture()), render_markdown(&fixture()));
        assert_eq!(render_json(&fixture()), render_json(&fixture()));
    }

    #[test]
    fn json_is_parseable_and_keeps_every_tool() {
        let v: Value = serde_json::from_str(&render_json(&fixture())).unwrap();
        assert_eq!(v.as_array().unwrap().len(), 2);
        assert_eq!(v[0]["name"], "zzz_read");
        assert_eq!(v[1]["tier"], "dangerous");
    }
}
